a = input('write something: ')
print('the primitive type of value is: ', type(a))
print('only have space? ', a.isspace())
print('is a number? ', a.isnumeric())
print('is alphabetic? ', a.isalpha())
print('is alphanumeric? ', a.isalnum())
print('is upper case? ', a.isupper())
print('is lower case? ', a.islower())
print('is title case? ', a.istitle())
